default_platform(:ios)

platform :ios do
  desc "Build and archive the app"
  lane :build do
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_filepath: "./AuthKey_#{ENV['API_KEY_ID']}.p8",
      duration: 1200, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
    
    match(type: "appstore", readonly: false, git_url: "https://github.com/DanielSakarli/dolphin_wet") # Fetches signing certificates and provisioning profiles from a Git repo

    gym(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      sdk: "iphoneos",
      configuration: "AppStoreDistribution",
      archive_path: "./build/App.xcarchive",
      clean: true, # Set to false to skip cleaning
      export_options: {
        method: "app-store",
        provisioningProfiles: {
            "com.dolphinwetapp.dolphinwet": "match AppStore com.dolphinwetapp.dolphinwet"
        }
      }
    )
  end
end