default_platform(:ios)

platform :ios do
  desc "Build and archive the app"
  lane :build do
    match(type: "appstore", readonly: false) # Fetches signing certificates and provisioning profiles from a Git repo

    gym(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      sdk: "iphoneos",
      configuration: "AppStoreDistribution",
      archive_path: "./build/App.xcarchive",
      clean: true, # Set to false to skip cleaning
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.dolphinwetapp.dolphinwet": ENV["PROVISIONING_PROFILE"]
        }
      }
    )
  end
end