# This workflow is executed on specific triggers and creates an .api file for
# the download on iOS devices. With this, there is no need for a macOS (virtual)
# machine with XCode to deploy the app for iOS. Still, an Apple Developer Account
# is needed to create the necessary certificates and provisioning profiles.

name: ios_distribution

on: [push] #, pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'

    - name: Install dependencies
      run: npm ci
      working-directory: Code/frontend

    #- name: Add iOS platform
    #  run: npx cap add ios
    #  working-directory: Code/frontend

    #- name: Sync with iOS platform
    #  run: npx cap sync ios
    #  working-directory: Code/frontend

    - name: Build Ionic App
      run: npm run build
      working-directory: Code/frontend

    - name: Copy to iOS platform
      run: npx cap copy
      working-directory: Code/frontend

    - name: Sync with iOS platform
      run: npx cap sync ios
      working-directory: Code/frontend

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install iOS dependencies
      run: |
        DEVELOPMENT_TEAM_ID=${{ secrets.DEVELOPMENT_TEAM_ID }}
        pod install
      working-directory: Code/frontend/ios/App
      env:
        DEVELOPMENT_TEAM_ID: ${{ secrets.DEVELOPMENT_TEAM_ID }}
        PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}

    - name: Install Fastlane
      run: sudo gem install fastlane -NV

    - name: Set Development Team ID and Enable Automatic Signing for All Targets
      run: |
        DEVELOPMENT_TEAM_ID=${{ secrets.DEVELOPMENT_TEAM_ID }}
        PROJECT_FILE_PATH="Code/frontend/ios/App/App.xcodeproj/project.pbxproj"
    
        if [ -z "$DEVELOPMENT_TEAM_ID" ]; then
          echo "Development Team ID is required"
          exit 1
        fi

        # Use sed to set the development team ID and enable automatic signing in the project file
        sed -i '' "s/DEVELOPMENT_TEAM = [^;]*;/DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM_ID;/g" $PROJECT_FILE_PATH
        sed -i '' "s/DevelopmentTeam = [^;]*;/DevelopmentTeam = $DEVELOPMENT_TEAM_ID;/g" $PROJECT_FILE_PATH
        sed -i '' "s/ProvisioningStyle = Manual;/ProvisioningStyle = Automatic;/g" $PROJECT_FILE_PATH
        sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = [^;]*;/ProvisioningStyle = Automatic;/g" $PROJECT_FILE_PATH
        sed -i '' "s/CODE_SIGN_IDENTITY = \"iPhone Developer\";/CODE_SIGN_IDENTITY = \"iPhone Distribution\";/g" $PROJECT_FILE_PATH
        
        # Ensure all targets are set to use automatic signing
        TARGETS=("CapacitorApp" "CapacitorKeyboard" "CapacitorHaptics")
        for TARGET in "${TARGETS[@]}"
        do
          sed -i '' "s/DEVELOPMENT_TEAM = [^;]*;/DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM_ID;/g" "$PROJECT_FILE_PATH"
          sed -i '' "s/DevelopmentTeam = [^;]*;/DevelopmentTeam = $DEVELOPMENT_TEAM_ID;/g" "$PROJECT_FILE_PATH"
          sed -i '' "s/ProvisioningStyle = Manual;/ProvisioningStyle = Automatic;/g" "$PROJECT_FILE_PATH"
          #sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = [^;]*;/ProvisioningStyle = Automatic;/g" "$PROJECT_FILE_PATH"
        done
    
        echo "Set DEVELOPMENT_TEAM to $DEVELOPMENT_TEAM_ID and enabled automatic signing in $PROJECT_FILE_PATH for all targets"

        # Verify the changes
        echo "Verifying the project file changes..."
        grep -C 3 "DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM_ID" $PROJECT_FILE_PATH
      shell: bash

    - name: Configure Git for Authentication
      run: |
        git config --global user.email "daniel-sakarli@hotmail.de"
        git config --global user.name "DanielSakarli"
        git remote set-url origin https://github.com/${{ github.repository }}
        git remote set-url --push origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Build and sign iOS App
      run: |
        echo "API_KEY_ID is set to: ${API_KEY_ID:0:2}***"
        MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }} fastlane ios build_debug
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        API_KEY_ID: ${{ secrets.API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
        API_AUTH_KEY: ${{ secrets.API_AUTH_KEY }}
        DEVELOPMENT_TEAM_ID: ${{ secrets.DEVELOPMENT_TEAM_ID }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        MATCH_BRANCH: ${{ secrets.MATCH_BRANCH }}
        PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: iOS App
        path: ${{ github.workspace }}/fastlane/build/App.xcarchive